apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name }}-db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app: {{.Release.Name }}
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: test123
  APP_DB_NAME: test
  APP_DB_SCHEMA: app
  APP_DB_USE: app
  APP_DB_PASSWORD: app123
  APP_DB_EXPIRATION: "2025-12-31 18:00:00"
  APP_DB_CONNECTION_LIMIT: "20"