kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{.Release.Name }}
  labels:
    type: local
    app: {{.Release.Name }}
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Release.Name }}
  labels:
    app: {{.Release.Name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
  resources:
    requests:
      storage: 8Gi
