apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name }}-db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app: {{.Release.Name }}
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: test123
  APP_DB_NAME: test
  APP_DB_USE: app
  APP_DB_PASSWORD: app123
  APP_DB_EXPIRATION: "2025-12-31 18:00:00"
  APP_DB_CONNECTION_LIMIT: "20"

spring.data.cassandra.schema-action=${DB_SCHEMA_ACTION:NONE}
spring.data.cassandra.request.timeout=${DB_REQUEST_TIMEOUT:10s}
spring.data.cassandra.connection.init-query-timeout=${DB_CONNECTION_INIT_QUERY_TIMEOUT:10s}
spring.data.cassandra.keyspace-name=${DB_KEYSPACE_NAME:auditSpace}
spring.data.cassandra.port=${DB_PORT:9042}
spring.data.cassandra.contact-points=${DB_HOST:127.0.0.1}
spring.data.cassandra.local-datacenter=${DB_LOCAL_DATACENTER:datacenter1}
spring.data.cassandra.username=${DB_USERNAME:cassandra}
spring.data.cassandra.password=${DB_PASSWORD:}  