#!/bin/bash

rm -rf $S3_CONF_FILE_PATH
S3_CONF_FILE_TEMPLARE_PATH_COPY=$S3_CONF_FILE_TEMPLARE_PATH"_copy"
cp $S3_CONF_FILE_TEMPLARE_PATH $S3_CONF_FILE_TEMPLARE_PATH_COPY

echo "access_key = $S3_ACCESS_KEY" >> $S3_CONF_FILE_TEMPLARE_PATH_COPY
echo "secret_key = $S3_SECRET_KEY" >> $S3_CONF_FILE_TEMPLARE_PATH_COPY
echo "host_base = $S3_HOST_BASE" >> $S3_CONF_FILE_TEMPLARE_PATH_COPY
echo "host_bucket = $S3_HOST_BUCKET" >> $S3_CONF_FILE_TEMPLARE_PATH_COPY
echo "website_endpoint = $S3_WEBSITE_ENDPOINT" >> $S3_CONF_FILE_TEMPLARE_PATH_COPY
echo "bucket_location = $S3_BUCKET_LOCATION" >> $S3_CONF_FILE_TEMPLARE_PATH_COPY

mv $S3_CONF_FILE_TEMPLARE_PATH_COPY $S3_CONF_FILE_PATH

echo "S3 client have been configured to use bucket: $S3_HOST_BUCKET"
