apiVersion: v1
kind: PersistentVolume
metadata:
  name: clamav-volume-lib-pv
  labels:
    type: local
    app: {{.Release.Name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data1"