apiVersion: v1
kind: Service
metadata:
  name: nginx-matrix-keycloak
  labels:
    app: nginx-matrix-keycloak
spec:
  type: NodePort
  selector:
      app: nginx-matrix-keycloak
  ports:
  - port: 555
    nodePort: 30950
    protocol: TCP
    name: nginx-http
  - port: 8080
    nodePort: 30951
    protocol: TCP
    name: keycloak-http
  - port: 8008
    nodePort: 30952
    protocol: TCP
    name: matrix-http

