apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-0
  labels:
    type: local
    app: {{.Release.Name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.elasticsearch.volumeClaimTemplate.resources.requests.storage}}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"

