FROM nginx:alpine

#RUN mkdir -p /etc/nginx/external
#COPY certs/nginxcert.pem /etc/nginx/external/nginxcert.crt
#COPY certs/nginxkey.pem /etc/nginx/external/nginxkey.pem

COPY nginx.conf /etc/nginx/nginx.conf


