apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-volume-lib-pvc
  labels:
    app: {{.Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
  volumeName: clamav-volume-lib-pv