apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-log-config-configmap
  labels:
    app: nginx-matrix-keycloak
data:
  matrix.log.config: |
    version: 1
    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
    loggers:
        synapse.storage.SQL:
            # beware: increasing this to DEBUG will make synapse log sensitive
            # information such as access tokens.
            level: INFO
    root:
        level: INFO
        handlers: [console]
    disable_existing_loggers: false  
    