apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.elasticsearch.backup.job.name}}-pv
  labels:
    type: local
    app: {{.Release.Name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
spec:
  storageClassName: {{.Values.elasticsearch.backup.volume.storageClassName}}
  capacity:
    storage: {{.Values.elasticsearch.backup.volume.storage}}
  accessModes:
    - {{.Values.elasticsearch.backup.volume.accessMode}}
  hostPath:
    path: "/mnt/data2"