apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.elasticsearch.backup.job.configName}}
data:
  snapshot.sh: |
    echo Creating a new snapshot...
    curl -s -o /dev/null -X PUT "$HOST:$LOCAL_PORT/_snapshot/$SNAPSHOT_REPOSITORY?pretty" -H 'Content-Type: application/json' -d'
    {
      "type": "fs",
      "settings": {
        "location": "/opt/backup"
      }
    }
    '
    sleep 1
    curl -s -X PUT "$HOST:$LOCAL_PORT/_snapshot/$SNAPSHOT_REPOSITORY/$SNAPSHOT_NAME?wait_for_completion=true&pretty"
    sleep 1
    echo
    echo "Available snapshots in $SNAPSHOT_REPOSITORY are: "
    echo
    curl -s -X GET "$HOST:$LOCAL_PORT/_cat/snapshots/$SNAPSHOT_REPOSITORY?v&s=id&pretty"
    sleep 10