apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:       
        - name: matomo
          image: matomo
          imagePullPolicy: IfNotPresent
          ports:
          - name: matomo-http
            containerPort: 80
            protocol: TCP
          env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: APACHE_HTTP_PORT_NUMBER
              value: '8080'
            - name: APACHE_HTTPS_PORT_NUMBER
              value: '8443'
            - name: MATOMO_DATABASE_HOST
              value: 'mysql'
            - name: MATOMO_DATABASE_PORT_NUMBER
              value: '3306'
            - name: MATOMO_DATABASE_NAME
              value: matomo
            - name: MATOMO_DATABASE_USER
              value: matomo
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: matomo-externaldb
            - name: MATOMO_SKIP_BOOTSTRAP
              value: 'no'
            - name: MATOMO_USERNAME
              value: admin
            - name: MATOMO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: matomo-password
                  name: matomo-user-admin-password
            - name: MATOMO_EMAIL
              value: hugo@gmail.com
            - name: MATOMO_WEBSITE_NAME
              value: matomo-test
            - name: MATOMO_WEBSITE_HOST
              value: 'http://localhost'
           
          volumeMounts:
            - mountPath: /var/www/html
              name: html-files
          #resources:
            #limits:
              #memory: 1000Mi
            #requests:
              #cpu: 500m
              #memory: 1000Mi   
          #livenessProbe:
            #httpGet:
              #path: /
              #port: 80
            #initialDelaySeconds: 5
            #periodSeconds: 5
      volumes:
      - name: html-files
        emptyDir: {}



            
