apiVersion: v1
kind: Service
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  type: NodePort
  selector:
      app: matomo
  ports:
  - port: 80
    nodePort: 30950
    protocol: TCP
    name: matomo-http

