apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{.Release.Name }}
  name: {{.Release.Name }}
type: Opaque
data:
  vault-url: {{ .Values.app.secrets.vaultAddr | b64enc }}
  vault-token: {{ .Values.app.secrets.vaultToken | b64enc }}
