apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.terraform.configMap.name }}
  labels:
    app: {{.Release.Name }}
data:
  main.tf: |
    provider "vault" {

    }

    resource "vault_generic_secret" "test_secret" {
      path         = "secret/test_secret"
      disable_read = false
      data_json = jsonencode({
        secret_a = "okok"
      })
    }
  terraform.sh: |
    #!/bin/bash
    echo "VAULT_ADDR=$VAULT_ADDR"
    echo "VAULT_TOKEN=$VAULT_TOKEN"
    cd /terraform
    ls
    rm -rf .terraform
    rm .terraform*
    rm terraform.tfstate
    terraform init
    terraform apply  -auto-approve -parallelism=2