apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.terraform.configMap.name }}
  labels:
    app: {{.Release.Name }}
data:
  providers.tf: |
    provider "vault" {
        skip_child_token = true
    }  
  variables.tf: |
    variable "vault_secret_path" {
      type        = string
      description = "Vault secret path."
    }  
    variable "db_name" {
      type        = string
      description = "Database name."
    }
    variable "db_username" {
      type        = string
      description = "Database Username."
    }
    variable "db_password" {
      type        = string
      description = "Database passwors."
    }
  main.tf: |
    terraform {
      required_version = "v1.1.7"
      required_providers {
        vault = {
          source  = "hashicorp/vault"
          version = "3.6.0"
        }
      }
    }    

    resource "vault_generic_secret" "test_secret" {
      path         = "secret/${var.vault_secret_path}"
      disable_read = false
      data_json = jsonencode({
        db_name = var.db_name,
        username = var.db_username,
        password = var.db_password
      })
    }
  terraform.sh: |
    #!/bin/bash
    echo "VAULT_ADDR=$VAULT_ADDR"
    echo "VAULT_TOKEN=$VAULT_TOKEN"
    cd /terraform
    ls
    rm -rf .terraform
    rm .terraform*
    rm terraform.tfstate
    terraform init
    terraform apply  -auto-approve -parallelism=2