

terraform:
    file: ${TERRAFORM_EXEC_FILE:terraform/terraform.sh}

server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}

spring:
  application:
    name: vault-terraform-springboot