apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name }}-init-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{.Release.Name }}
data:
  config-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
      CREATE EXTENSION IF NOT EXISTS "pgcrypto";
      CREATE DATABASE "$APP_DB_NAME";
      CREATE USER ${APP_DB_USE} WITH PASSWORD '${APP_DB_PASSWORD}' VALID UNTIL '${APP_DB_EXPIRATION}' CONNECTION LIMIT ${APP_DB_CONNECTION_LIMIT};
      GRANT CONNECT ON DATABASE ${APP_DB_NAME} TO ${APP_DB_USE};
    EOSQL