kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{.Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    type: local
    app: {{.Release.Name }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{.Release.Name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi