version: '3.9'


services:


  nginx-customer-x:
    build: 
      context: ./customer-x
    container_name: nginx-customer-x
    restart: on-failure
    ports:
      - '445:445'
      - '81:81'
    command: [ nginx, '-g', 'daemon off;' ]
    networks:
      - nginx-private-certificate-network
    depends_on:
      - nginx-customer-y

  nginx-customer-y:
    build: 
      context: ./customer-y
    container_name: nginx-customer-y
    restart: on-failure
    ports:
      - '446:446'
      - '82:82'
    command: [ nginx, '-g', 'daemon off;' ]
    networks:
      - nginx-private-certificate-network

    
networks:
  nginx-private-certificate-network:
    driver: bridge
    name: nginx-private-certificate-network
#  kind:
#    external: true

volumes:
  nexus-sonatype-work:
    name: devops-nexus-sonatype-work


